### PR TITLE
ci: enable cd

### PR DESCRIPTION
**Pull request by viceice**
### Testing done

```[tasklist]
### Submitter checklist
- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by jglick** [comment]
I think in #5 you forgot to add the required files to `.mvn/`. Recheck https://www.jenkins.io/doc/developer/publishing/releasing-cd/#incrementals-enablement

**Comment by viceice** [comment]
> I think in #5 you forgot to add the required files to `.mvn/`. Recheck https://www.jenkins.io/doc/developer/publishing/releasing-cd/#incrementals-enablement

Added in #7 🙃

**Comment by jglick** [comment]
OK…though `changelist.format` is specific to CD, so this was a bit mixed up.

**Comment by viceice** [comment]
Ok. didn't know. I'm new to this kind of jenkins automation 🙃 Will try to remember when adopting other plugins.

**Pull request merged**
