### PR TITLE
Modernize plugin

### PR DESCRIPTION
**Pull request by viceice**
Modernize plugin to compile with java 17 / 21

### Testing done
Just compile with java 17 / 21 and uploaded to jenkins

```[tasklist]
### Submitter checklist
- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

### CODE REVIEW

**Comment by viceice** [comment]
@jglick Any chance to review this?

**Comment by jglick** [comment]
I am not a maintainer; probably there is none. [Adopt it](https://www.jenkins.io/doc/developer/plugin-governance/adopt-a-plugin/) if you want.

**Comment by viceice** [comment]
OK will do that.

btw: you are set as developer 🙃 

https://github.com/jenkins-infra/repository-permissions-updater/blob/9b3269169b18ead04b20dd27a3ec541b8f458c88/permissions/plugin-additional-identities-plugin.yml#L9

**Comment by jglick** [comment]
That may be for historical reasons. I do not in fact have write access to the repository.

**Comment by jglick** [comment]
(https://github.com/jenkins-infra/repository-permissions-updater/commit/a67361937ced805d4873b3637df278e2d65effc5, perhaps based on https://github.com/jenkinsci/additional-identities-plugin/commit/451b411c48076b201b8c353c454b024f7a9ca0e8, my sole “contribution”.)

**Comment by viceice** [comment]
ok, will open adoption Pr tomorrow 🤗

**Comment by viceice** [comment]
- https://github.com/jenkins-infra/repository-permissions-updater/pull/3808

🤗

**Pull request merged**
